- name: variables in ansible
  hosts: localhost
  # creating the variables
  vars_files:
  - variables.yaml
  tasks:
  - name: Print the variables
    ansible.builtin.debug:
      msg: "I am learning Ansible"
  - name: Print the msg
    ansible.builtin.debug:
      msg: "Hello This {{NAME}}, Working as a {{COURCE}} engineer, Thanks!!"